/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author chave
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public ventanaPrincipal() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Maximiza la ventana principal
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jRegistroEstudiante = new javax.swing.JMenu();
        jRecolecionDatos = new javax.swing.JMenu();
        jVisualicionDatos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 255));

        jRegistroEstudiante.setText("Registro Estudiante");
        jRegistroEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickRegistro(evt);
            }
        });
        jMenuBar1.add(jRegistroEstudiante);

        jRecolecionDatos.setText("Recoleccion de Datos");
        jRecolecionDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRecolecionDatosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jRecolecionDatos);

        jVisualicionDatos.setText("Visualizacion de Datos");
        jVisualicionDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVisualicionDatosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jVisualicionDatos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickRegistro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickRegistro
        // TODO add your handling code here:
        ventanaRegistroEstudiante registroEstudiante = new ventanaRegistroEstudiante();
        registroEstudiante.setVisible(true);
    }//GEN-LAST:event_clickRegistro

    private void jRecolecionDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRecolecionDatosMouseClicked
        // TODO add your handling code here:
        ventanaRecolecionDatos recolecionDatos = new ventanaRecolecionDatos();
        recolecionDatos.setVisible(true);
    }//GEN-LAST:event_jRecolecionDatosMouseClicked

    private void jVisualicionDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVisualicionDatosMouseClicked
        // TODO add your handling code here:
        ventanaVisualizacion ventanaVisualizacion = new ventanaVisualizacion();
        ventanaVisualizacion.setVisible(true);
    }//GEN-LAST:event_jVisualicionDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }
    
     
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu jRecolecionDatos;
    public javax.swing.JMenu jRegistroEstudiante;
    public javax.swing.JMenu jVisualicionDatos;
    // End of variables declaration//GEN-END:variables
}
